// <auto-generated />
using System;
using CP2_CS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CP2_CS.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260506012200_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CP2_CS.Domain.Entities.Agencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<int>("Numero")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("TB_AGENCIA", (string)null);
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AgenciaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("TB_CLIENTE", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Cliente");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Contratacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("DataProcessamento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("Status")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("TB_CONTRATACAO", (string)null);
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("NVARCHAR2(21)");

                    b.HasKey("Id");

                    b.ToTable("TB_PRODUTO", (string)null);

                    b.HasDiscriminator<string>("Tipo").HasValue("Produto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.PessoaFisica", b =>
                {
                    b.HasBaseType("CP2_CS.Domain.Entities.Cliente");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasFilter("\"Cpf\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PF");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.PessoaJuridica", b =>
                {
                    b.HasBaseType("CP2_CS.Domain.Entities.Cliente");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)");

                    b.HasIndex("Cnpj")
                        .IsUnique()
                        .HasFilter("\"Cnpj\" IS NOT NULL");

                    b.HasDiscriminator().HasValue("PJ");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Emprestimo", b =>
                {
                    b.HasBaseType("CP2_CS.Domain.Entities.Produto");

                    b.Property<int>("PrazoMeses")
                        .HasColumnType("NUMBER(10)");

                    b.Property<decimal>("TaxaJurosMensal")
                        .HasColumnType("NUMBER(10,4)");

                    b.Property<decimal>("ValorSolicitado")
                        .HasColumnType("NUMBER(15,2)");

                    b.HasDiscriminator().HasValue("EMPRESTIMO");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.MaquinaDeCartao", b =>
                {
                    b.HasBaseType("CP2_CS.Domain.Entities.Produto");

                    b.Property<decimal>("TaxaMDR")
                        .HasColumnType("NUMBER(10,4)");

                    b.Property<int>("TipoPagamento")
                        .HasColumnType("NUMBER(10)");

                    b.HasDiscriminator().HasValue("MAQUINA_CARTAO");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CP2_CS.Domain.Entities.Agencia", "Agencia")
                        .WithMany("Clientes")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Contratacao", b =>
                {
                    b.HasOne("CP2_CS.Domain.Entities.Cliente", "Cliente")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CP2_CS.Domain.Entities.Produto", "Produto")
                        .WithMany("Contratacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Agencia", b =>
                {
                    b.Navigation("Clientes");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Contratacoes");
                });

            modelBuilder.Entity("CP2_CS.Domain.Entities.Produto", b =>
                {
                    b.Navigation("Contratacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
